# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "CI"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:

  composer-require-checker:
    name: "composer-require-checker"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "shivammathur/setup-php@v2"
        with: { coverage: "none", php-version: "8.1" }

      - uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "lowest"
          working-directory: api

      - name: "Run composer-require-checker"
        working-directory: api
        run: "vendor/bin/composer-require-checker"

  phpcs:
    name: "phpcs"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "shivammathur/setup-php@v2"
        with: { coverage: "none", php-version: "8.1" }

      - uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "highest"
          working-directory: api

      - name: "Run phpcs"
        working-directory: api
        run: "vendor/bin/phpcs"

  static-analysis-psalm:
    name: "Static Analysis with Psalm"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "shivammathur/setup-php@v2"
        with: {coverage: "none", php-version: "8.1"}

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "highest"
          working-directory: api

      - name: "Run a static analysis with vimeo/psalm"
        working-directory: api
        run: "vendor/bin/psalm --show-info=false --stats --output-format=github --threads=$(nproc)"

  static-analysis-phpstan:
    name: "Static Analysis with PHPStan"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "shivammathur/setup-php@v2"
        with: {coverage: "none", php-version: "8.1"}

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "highest"
          working-directory: api
          run: "vendor/bin/phpstan"

  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "shivammathur/setup-php@v2"
        with: { coverage: "none", php-version: "8.1" }

      - uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "highest"
          working-directory: api

      - name: "Run phpunit"
        working-directory: api
        run: "vendor/bin/phpunit"